version: "3"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: lender
    container_name: api
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - lender_net
  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql/data
    networks:
      - lender_net

networks:
  lender_net:
